// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjV6765KGXNMkpMVyn-Oi1662ANKW6ebE',
    appId: '1:244393343345:android:940d717085204d2c62ded0',
    messagingSenderId: '244393343345',
    projectId: 'fir-flutter-96228',
    storageBucket: 'fir-flutter-96228.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM_l7bLpnTEffgmu0rSnviOKput9G4JjY',
    appId: '1:244393343345:ios:b4935d91d83ca44562ded0',
    messagingSenderId: '244393343345',
    projectId: 'fir-flutter-96228',
    storageBucket: 'fir-flutter-96228.firebasestorage.app',
    iosBundleId: 'com.example.webDynamicFormFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM_l7bLpnTEffgmu0rSnviOKput9G4JjY',
    appId: '1:244393343345:ios:b4935d91d83ca44562ded0',
    messagingSenderId: '244393343345',
    projectId: 'fir-flutter-96228',
    storageBucket: 'fir-flutter-96228.firebasestorage.app',
    iosBundleId: 'com.example.webDynamicFormFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhERqt0Ws0Gf0w9JxoH-ph-0B_WqSvYxg',
    appId: '1:244393343345:web:a1406d46567442c462ded0',
    messagingSenderId: '244393343345',
    projectId: 'fir-flutter-96228',
    authDomain: 'fir-flutter-96228.firebaseapp.com',
    storageBucket: 'fir-flutter-96228.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhERqt0Ws0Gf0w9JxoH-ph-0B_WqSvYxg',
    appId: '1:244393343345:web:a1406d46567442c462ded0',
    messagingSenderId: '244393343345',
    projectId: 'fir-flutter-96228',
    authDomain: 'fir-flutter-96228.firebaseapp.com',
    storageBucket: 'fir-flutter-96228.firebasestorage.app',
  );

}